### ISSUE TITLE
new erigon node stacked in `starting` stage

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-service-erigon#15]
Name: Mateusz
OS+lang+version (if applicable): 
Title: new erigon node stacked in `starting` stage
!!! attach `blender-yapapi.log`, zipped data-dir !!!

```
    Janek says it is provider 1
```

**Comment by johny-b** [comment]
I've seen this twice and both times this was `erigon-1`.
I'll be investigating this.

**Comment by johny-b** [comment]
@shadeofblue says this might be connected to https://github.com/golemfactory/yapapi/issues/392

our "starting" state is after agreement is signed, and if the provider breaks the agreement (or maybe something unexpected happens, like 408? --> https://github.com/golemfactory/yapapi/issues/415 ) between this moment and first yield in run() we'll be stuck in "starting" state

**Comment by johny-b** [comment]
I think this is solved in the current `yapapi` master (to-be-released in the next patch)
