### ISSUE TITLE
 button `stop node` is not working when the node is pending

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-service-erigon#17]
in web service it is not possible to stop pending node, when hitting "stop button"

![Screenshot from 2021-06-08 15-44-47](https://user-images.githubusercontent.com/32061891/121201734-083ee300-c875-11eb-9234-9395d02ca319.png)

no errors in console regarding stopping

eventually node has stopped, but it took long time, in interface it showed no indication of stopping

**Comment by nataliakulas** [comment]
@ederenn From the screenshot above we can't see what is happening with the requests step by step. 

Please attach something like video below, where we can see what is sending and what is received. 
Also, as you can see, I still cannot reproduce this bug. Maybe it was temporary problem with cors? (but then all requests should have been failing).

![2021-06-08 18 29 19](https://user-images.githubusercontent.com/23013269/121223508-e4d16380-c887-11eb-98e3-cb9ee3b33d10.gif)

**Comment by johny-b** [comment]
Solved in 7f14703.

Nodes were correctly stopped, but status sent to the frontend was incorrect.
